### ISSUE TITLE
Create iso from script

### ISSUE THREAD

**Issue by walabus** [offensive-security/kali-linux-recipes#1]
Hi,

I get the following error message running the script.

P: Considering defaults defined in /etc/live/build.conf
live-build: unrecognized option '--cdebootstrap-options'
live-build: unrecognized option '--updates'
live-build: unrecognized option '--firmware-binary'
live-build: unrecognized option '--firmware-chroot'

Any ideas on how to resolve this?

**Comment by thebunnyrules** [comment]
I'm having the same issues but for another Distro than Kali. 

From what I've observed: using live-build is not an installer type deal where you run a script in the terminal and it asks you a whole bunch of questions and it pumps out an iso for you. I think you're supposed to have a basic grasp of how to use Debian's live-build and setup the options/packages you want in your ISO via the conf scripts provided in distro folder you've downloaded before running the lb conf and lb build command.

There are lots of tutorials on debian live-build. You can start with this one:
http://www.debianuserforums.org/viewtopic.php?f=9&t=185

I'm just
